import {createHash} from 'node:crypto';
import {mkdir,readFile,readdir,writeFile} from 'node:fs/promises';
import {dirname,join,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {renderAmbiguity,renderEntity,renderIndex,escapeText,type Obj} from './render.js';
import type {Config,BuildEntry,ManifestPage,ExportManifest} from './types.js';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..'),dataRoot=join(root,'site/public/data'),outRoot=join(root,'mediawiki/output');
const config=JSON.parse(await readFile(join(root,'mediawiki/config.json'),'utf8')) as Config;
const digest=(s:string)=>createHash('sha256').update(s).digest('hex');
const typeNames:Record<string,string>={missions:'Missions',npcs:'NPCs',items:'Items','item-sets':'Item sets',codes:'Codes',monsters:'Monsters',areas:'Areas',instances:'Instances','infected-zones':'Infected zones',nanos:'Nanos','player-stats':'Player stats'};
const refTypes:Record<string,string>={mission:'missions',npc:'npcs',item:'items','item-set':'item-sets',code:'codes',monster:'monsters',area:'areas',instance:'instances','infected-zone':'infected-zones',nano:'nanos'};
const clean=(v:unknown)=>String(v??'Unnamed').replace(/[#[\\\]{}|<>\n\r\t]/g,' ').replace(/\s+/g,' ').trim()||'Unnamed';
const readJson=async<T>(path:string)=>JSON.parse(await readFile(path,'utf8')) as T;
const chunkCache=new Map<string,Record<string,Obj>>();
async function chunk(path:string){const old=chunkCache.get(path);if(old)return old;const loaded=await readJson<Record<string,Obj>>(path);if(chunkCache.size>=24)chunkCache.clear();chunkCache.set(path,loaded);return loaded}
function pageTitle(build:string,type:string,name:unknown,id:unknown,collides=false){return clean(build)+'/'+(typeNames[type]||clean(type))+'/'+clean(name||id)+(collides?' ('+clean((typeNames[type]||type).replace(/s$/,''))+' '+clean(id)+')':'')}
async function addPage(title:string,build:string,type:string,body:string,pages:ManifestPage[]){const path=join('pages',build,type,digest(title).slice(0,24)+'.wiki');await mkdir(dirname(join(outRoot,path)),{recursive:true});await writeFile(join(outRoot,path),body);const sections=[...body.matchAll(/^== ([^=\n]+) ==\n<!-- OFAW:([^:>]+):v\d+ -->\n([\s\S]*?)(?=^== |$)/gm)].map(m=>({heading:m[1],key:m[2],hash:digest(m[3])}));pages.push({title,path,hash:digest(body),build,type,sections,media:[]})}
async function main(){await mkdir(outRoot,{recursive:true});const builds=await readJson<BuildEntry[]>(join(root,'site/public/builds.json'));const pages:ManifestPage[]=[];
for(const build of builds){if(process.env.MEDIAWIKI_BUILD&&process.env.MEDIAWIKI_BUILD!==build.slug)continue;const dir=join(dataRoot,build.slug,'index'),files=(await readdir(dir)).filter(f=>f.endsWith('.json'));const indexes=new Map<string,Obj[]>(),routes=new Map<string,Record<string,Obj>>(),titles=new Map<string,string>();
for(const file of files){const type=file.slice(0,-5),rows=await readJson<Obj[]>(join(dir,file));indexes.set(type,rows);if(type==='player-stats')continue;const map=await readJson<Record<string,Obj>>(join(dataRoot,build.slug,'routes',file));routes.set(type,map);for(const [segment,target] of Object.entries(map)){if(target.kind==='entity'&&segment===target.canonical){const row=rows.find(r=>String(r.id)===String(target.id))||rows.find(r=>Array.isArray(r.members)&&(r.members as Obj[]).some(m=>String(m.id)===String(target.id)));const name=row?.name??row?.code??target.id;const collision=segment!==clean(String(name).toLowerCase().replace(/[^a-z0-9]+/g,'-')).replace(/^-|-$/g,'');titles.set(type+':'+target.id,pageTitle(build.displayName,type,name,target.id,collision))}else if(target.kind==='ambiguity'&&segment===target.canonical)titles.set(type+':ambiguity:'+segment,pageTitle(build.displayName,type,target.title,segment))}}
const link=(value:unknown)=>{const ref=value as Obj,type=refTypes[String(ref.type)]||String(ref.type),title=titles.get(type+':'+ref.id)||pageTitle(build.displayName,type,ref.name,ref.id);return '[['+title+'|'+escapeText(ref.name??ref.id)+']]'};
for(const [type,rows] of indexes){const indexTitle=clean(build.displayName)+'/'+(typeNames[type]||clean(type));if(type==='player-stats'){await addPage(indexTitle,build.slug,type,renderIndex(type,rows,r=>escapeText(r.level??r.id),config,[build.displayName,typeNames[type]]),pages);continue}const map=routes.get(type)!;const rowLink=(row:Obj)=>{const target=map[String(row.routeId??row.id)];const title=target?.kind==='ambiguity'?titles.get(type+':ambiguity:'+target.canonical):titles.get(type+':'+(target?.id??row.id));return '[['+(title||pageTitle(build.displayName,type,row.name??row.code,row.id))+'|'+escapeText(row.name??row.code??row.id)+']]'};await addPage(indexTitle,build.slug,type,renderIndex(type,rows,rowLink,config,[build.displayName,typeNames[type],'OpenFusion AutoWiki indexes']),pages);
for(const [segment,target] of Object.entries(map)){if(segment!==target.canonical)continue;if(target.kind==='ambiguity'){const title=titles.get(type+':ambiguity:'+segment)!;await addPage(title,build.slug,type,renderAmbiguity(type,target.matches as Obj[],link,config,[build.displayName,typeNames[type],'Disambiguation pages']),pages);continue}const bucket=await chunk(join(dataRoot,build.slug,type,String(target.chunk)+'.json')),entity=bucket[String(target.id)];if(!entity)continue;const title=titles.get(type+':'+target.id)!;const cats=[build.displayName,typeNames[type]];for(const key of ['rarity','type','displayType','category','areaZone','nanoType'])if(entity[key])cats.push(String(entity[key]));await addPage(title,build.slug,type,renderEntity(type,entity,link,config,cats),pages)}}chunkCache.clear()}
const shards=[];const shardDir=join(outRoot,'shards');await mkdir(shardDir,{recursive:true});for(let i=0;i<pages.length;i+=config.shardSize){const shardPages=pages.slice(i,i+config.shardSize),id=String(i/config.shardSize).padStart(6,'0'),path=join('shards',id+'.json');await writeFile(join(outRoot,path),JSON.stringify(shardPages));shards.push({id,hash:digest(shardPages.map(page=>page.hash).join('')),path,pageCount:shardPages.length})}const manifest:ExportManifest={schemaVersion:config.schemaVersion,generatedAt:new Date().toISOString(),pageCount:pages.length,shards,media:[]};await writeFile(join(outRoot,'manifest.json'),JSON.stringify(manifest,null,2));console.log('MediaWiki export: '+pages.length+' pages, '+shards.length+' shards')}
await main();
